dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - jruby-9.1.15.0
  - ruby-head
  - jruby-head
env:
  global:
    secure: "Hfal+yUT5IjdHvx9EXChJveD6DKhExDxvtdkLe585egSMzW0p6oujFTpLD2EyGPV6Yyfyd/SijTKrgOgOsuXeBAKs9XSjy5HLLaieXoSnRordOPtp1xujm9T1l5oi1xmoh8fS1c/RliMtspHmMXpyEngwuVS8o0h4AUCK+VE+f9Wap90mE+sH/sZr3Dt7lQd0f+9dyCK5U/zpiyZVTPNHlJyHewudBlNq2dDN16ldF14SKcBxXmZIFP8FpF+gax8XjjjBwr247qzXyEUUC9CfRBiBIP6Cdv62E+KefGLI09I48KdYVDA0221mtYuqLONJv2JyXfxSi3kSAFCVKywNLj4HuR/ixnQ8VKFHkltRu6VTzr47OQbn+83u65r1YP14doTHo8RaiL5/CfmdnNptsgE3AxHNYV4ekizCWv2tt5fOSV2F4z3JICLDY1gCElOGYjfmoBxhmCIrF9h2V1RQnCefu3AnJZ2cUbCkLnaz39dROD0kWAkml0E3mvYt6vkqOkraRB+kmjcqtIGyjfgN2HfJeFMQpqbAyB9vCBvn0/ki3eeHnHDugb0A4e7NfAwgvFFKTwHddm9zaCpEblSQRQ5027eUs3c6fNxQGO5Yl6UP6QY5tycNhZrvYtuoqkz5648DZX+X9el8KT7e0SVgFu6AWbvtC2q0uifjSHD4ao="  # CODACY_PROJECT_TOKEN
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
script:
  - bundle exec rake spec
  - bundle exec rake rubocop
deploy:
  provider: rubygems
  api_key:
    secure: "CzuNFI2TO4Biq3QWiruJHVrexEtzDNbZDDtY3tA4DY12ATmQCtH4jBKIoSZxos3Bca+ZhjH7puOwWBwUf8wLyGtuWe2KmQQd48IWd0G3mmRexMeNDwbR+D8NpeYrJRtz0E/SEn02lCV5rm0MWqEf6tI23v0HB69CQSAN8b7JMtBOrodhk8fJh6yqbmzDHiiKS79Y7pfj3BaFoml56uPyNl5qO1qwnPM2JnKNEazbXq3F4meY7XLKJVR+Koz6Ia1wZRq67CmTAA39oqzcQSlvvosxXGKs/3Hozvnr83pYn/OTgUKS1Dj0JEpK9eo0zxUlW8nya/75RrCgyrfmMB7T6p5hWHJHMv06WUDxbQDMSkB45N94hX0dl6V5DZJgemNDAD3fkttfnq1L7j2g2oA+y8zsa/aWP9epAfIMMMBJCBBcS3k2x6Qwf6B4Ni9wx+vcvfujHLesdCvnpMqjZAnOsXYeUvB1gG7PahcLz3h0L54Df5tdrrjSPIAEO7oLCL5xPA6hG04tQdyeIk6TtWpLlpMN+73zOn+cQxOjHcYhPh78DqQ5eeWRDsrNNCFcaMOo1xK3XNIiRnX/qdMdHFWOB9Cr0J9jIXJg0cIAsGSZsXTAklPnDZYFAjKzyS4iswQE72gs6bG8hWpUutgCh4v47MZGTUcCDfbKfEOrODaPbx4="
  on:
    rvm: 2.4
    tags: true
